shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/image": ^2.0.0
  "@nuxt/kit": ^4.3.0
  "@nuxt/module-builder": ^1.0.2
  "@pinia/nuxt": ^0.11.3
  "@types/node": ^25.0.10
  "@unocss/nuxt": ^66.6.0
  "@vueuse/core": ^14.1.0
  "@vueuse/nuxt": ^14.1.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.4.0
  eslint: ^9.39.2
  nuxt: ^4.3.0
  pinia: ^3.0.4
  sass-embedded: ^1.97.3
  unocss: ^66.6.0
  vue: ^3.5.27
  vue-router: ^4.6.4
  vue-tsc: ^3.2.4

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
