shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/image": ^2.0.0
  "@nuxt/kit": ^4.2.2
  "@nuxt/module-builder": ^1.0.2
  "@pinia/nuxt": ^0.11.3
  "@types/node": ^25.0.3
  "@unocss/nuxt": ^66.5.10
  "@vueuse/core": ^14.1.0
  "@vueuse/nuxt": ^14.1.0
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.3
  eslint: ^9.36.0
  nuxt: ^4.2.2
  pinia: ^3.0.4
  sass-embedded: ^1.97.0
  unocss: ^66.5.10
  vue: ^3.5.26
  vue-router: ^4.6.4
  vue-tsc: ^3.1.8
  zx: ^8.8.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
